#pragma once

#include "Pipeline/Internal/PipelineFilter.h"

#include <fstream>

// Detects and logs blinks generated by BlinkerSource for latency measurements
class CITHRUS_API BlinkDetector : public PipelineFilter<1, 1>
{
public:
	BlinkDetector(const std::string& logPath = "");
	virtual ~BlinkDetector();

	virtual void Process() override;
	virtual void OnInputPinsConnected() override;

protected:
	const uint8_t* outputFrame_;
	uint32_t outputSize_;

	bool isWhite_;

	std::ofstream logStream_;
};
